version: "3.8"

services:
  postgres-db:
    container_name: modB # change this
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: acc_dev
      POSTGRES_PASSWORD: acc_dev12
      POSTGRES_DB: modB_db # change this
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5418:5432" # change this
    volumes:
      - postgresql_data:/var/lib/postgresql


volumes:
  postgresql_data:
    driver: local
