CREATE TABLE entry
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by_id BIGINT,
    title         VARCHAR(255)                            NOT NULL,
    message       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_entry PRIMARY KEY (id)
);

CREATE TABLE entry_images
(
    entry_id          BIGINT NOT NULL,
    entry_image_value VARCHAR(255)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    last_login TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE entry
    ADD CONSTRAINT uc_entry_title UNIQUE (title);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE entry
    ADD CONSTRAINT FK_ENTRY_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id);

ALTER TABLE entry_images
    ADD CONSTRAINT fk_entry_images_on_entry FOREIGN KEY (entry_id) REFERENCES entry (id);